# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qhztp7UJm11_3uxOheKQq0nlkqElkCHL
"""

!pip install streamlit -q

!wget -q -O - ipv4.icanhazip.com

!ls

!ls